TEMPLATEROOT = /home/m/CortexMCourse/STM32-Template

# additional compilation flags
CFLAGS += -O0  -g3
ASFLAGS += -g

# project files
OBJS = $(STARTUP) main.o

# include common make file
include $(TEMPLATEROOT)/Makefile.common
