TEMPLATEROOT = /home/m/CortexMCourse/STM32-Template

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g

# object files

OBJS=  $(STARTUP) main.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common
